### ISSUE TITLE
The breadcrumb's documentation page is mising

### ISSUE THREAD

**Issue by GribouilleVert** [Airmime/minstyle.io#27]
On the documentation, the page https://minstyle.io/docs/breadcrumbs is linked from the button and avatar page but return a 404 error.

**Comment by Airmime** [comment]
Hi GribouilleVert,

Thanks for your issue 😃 
Indeed, I will fixe that in V1.0.1.

Thanks again

**Comment by GribouilleVert** [comment]
No problems, happy to help !

**Comment by Airmime** [comment]
Issue resolve in V1.0.1.
