### ISSUE TITLE
Card content [Suggestion]

### ISSUE THREAD

**Issue by GribouilleVert** [Airmime/minstyle.io#32]
Event if card are generally ment for text; they often are used to display other contents such as form,

Therefor I sugggest to rename the `.ms-card-text` to `.ms-card-content` or to create this class wich would be used for non text content or content with more than text.

**Comment by Airmime** [comment]
Thanks for you feedback.

Yes, that does seem more appropriate. I'll make the modification in V1.0.2.

Thanks :)
