### ISSUE TITLE
File upload button looks broken 

### ISSUE THREAD

**Issue by viktor02** [Airmime/minstyle.io#35]
Chrome/Firefox
![05347](https://user-images.githubusercontent.com/19672960/126870181-1aa22741-6dde-4217-b2d8-cf9fda154e43.png)
![05348](https://user-images.githubusercontent.com/19672960/126870182-a0fc3e57-3a1e-409f-90ec-22c6770e283d.png)
CSS latest from cdn
```
<input type=file name=file>
```

**Comment by Airmime** [comment]
Hello,

Thanks for message.
I will fix that in V1.1.1.

Rémi
