### ISSUE TITLE
Chips

### ISSUE THREAD

**Issue by pspeter3** [Airmime/minstyle.io#37]
I love the styles in v2. I wonder if it would be possible to support something a Chips version of a radio / checkbox. For example, the toggle buttons in Bootstrap v5 https://getbootstrap.com/docs/5.1/forms/checks-radios/#toggle-buttons

**Comment by Airmime** [comment]
Hi,

It sound interesting, I'll look into for V2.0.1 ;)

**Comment by pspeter3** [comment]
Thanks!

**Comment by pspeter3** [comment]
The labels look great!
